### ISSUE TITLE
Click the icon to report an error

### ISSUE THREAD

**Issue by steven-wan** [ByteLegend/ByteLegend#13]
now I have no star and I click learn github pull request the icon,The game screen goes black，F12，show "NoSuchElementException: Key MissionDiscussion is missing in the map.
    at Object.t.captureStack (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:1414758)
    at jn.gn [as constructor] (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:1279343)
    at jn.bn [as constructor] (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:1279406)
    at vn (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:1279510)
    at new jn (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:1280309)
    at rs (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:1358718)
    at hu.getValue_t9ocha$ (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:1424942)
    at Game.i_60y5e1$ (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:500846)
    at MissionModal.GameUIComponent.i_60y5e1$ (https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:767116)
    at https://cdn.bytelegend.com/20210528134817/js/game-page.js:2:735796"

**Comment by blindpirate** [comment]
Fixed.
